name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ "dev" ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '14.16.0'
      - run: npm i express eslint
      - run: eslint index.js
      
      - name: Check ls
        run: ls
 
